name: winget

on:
  workflow_dispatch:
  push:
    paths:
      - 'winget/make.ps1'
      - '.github/workflows/winget.yml'

jobs:
  publish:
    runs-on: windows-latest
    env:
      WINGETCREATE_TOKEN: ${{ secrets.WINGETCREATE_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Submit
        run: |
          Set-Location winget
          ./make.ps1 --Submit --Token $env:WINGETCREATE_TOKEN
