name: winget

on:
  workflow_dispatch

jobs:
  publish:
    runs-on: windows-latest
    env:
      WINGETCREATE_TOKEN: ${{ secrets.WINGETCREATE_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Submit       
        run: winget/make.ps1 --Submit
